### ISSUE TITLE
customizing bpmnjs webjar for locking down functionalities

### ISSUE THREAD

**Issue by ersigcha23** [bpmn-io/webjar-bpmn-js#6]
Hi

Is there any way to customize the bpmn modeler to lock down some functionalities like https://bpmn.io/blog/posts/2015-locking-down-bpmn-js.html?

Thanks

**Comment by nikku** [comment]
Unfortunately no.

Customizing always means you'd effectively need to build your own, [customized bundle of bpmn-js](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-bower-bundle).
